name: docker_build_server

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/server/
          push: true
          tags: |
              cityofcapetown/cape-of-good-place-names:${GITHUB_REF##*/}
      -
        name: Build and push latest
        if: github.ref == "master"
        uses: docker/build-push-action@v2
        with:
          context: src/server/
          push: true
          tags: |
              cityofcapetown/cape-of-good-place-names:latest
