name: docker_build_server

on:
  workflow_dispatch:
  push:
    branches:
      - '*'
    tags:
      - '*'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Santise branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${steps.extract_branch.outputs.branch//\//_})"
        id: sanitise_branch
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/server/
          push: true
          tags: |
              cityofcapetown/cape-of-good-place-names:${{ steps.sanitise_branch.outputs.branch }}
      -
        name: Build and push latest
        if: ${{ steps.extract_branch.outputs.branch }} == 'master'
        uses: docker/build-push-action@v2
        with:
          context: src/server/
          push: true
          tags: |
              cityofcapetown/cape-of-good-place-names:latest
